### ISSUE TITLE
App installation failed: Unable to Install  Xcode 15.3

### ISSUE THREAD

**Issue by learnwithgabbar** [pingidentity/pingone-signals-sdk-ios#1]
After updating to Xcode 15.3, I encountered issues installing the app on the simulator and the device.

`Please try again later. Failed to load Info.plist from bundle at path /Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework; Extra info about "/Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework/Info.plist": Couldn't stat /Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework/Info.plist: No such file or directory`

**Comment by yizharkatif** [comment]
> After updating to Xcode 15.3, I encountered issues installing the app on the simulator and the device.
> 
> `Please try again later. Failed to load Info.plist from bundle at path /Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework; Extra info about "/Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework/Info.plist": Couldn't stat /Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework/Info.plist: No such file or directory`

Thanks for reaching out. Have you made sure the SDK exists in your workspace? Just to make sure I've just verified that Xcode 5.3 works properly.
Please follow [our guide](https://apidocs.pingidentity.com/pingone/native-sdks/v1/api/#pingone-protect-sdk-for-ios) for adding the SDK either with CocoaPods or Swift Package Manager.

**Comment by learnwithgabbar** [comment]
We have done all the setups as per the documentation. We are already using the SDK in our project and it is working fine in XCode 15.2 and below and the installation method is SPM

**Comment by yizharkatif** [comment]
Sorry for the obvious, however please try to do the following on Xcode 5.3 -
1. Remove the package.
2. Clean build.
3. Delete derived data folder.
4. Add it again (the package).

Of course LMK if something is unclear on these steps, or any other thing.

**Comment by learnwithgabbar** [comment]
@yizharkatif  Performed the above step and nothing changed

**Comment by learnwithgabbar** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/12390 for a quick reference

**Comment by yizharkatif** [comment]
Thanks, indeed reproduced, we'll keep you posted with the solution/workaround.

**Comment by yizharkatif** [comment]
Hi, it's something with SPM & Xcode 5.3 as Cocoa Pods and local configuration works.

Please try in the meantime (till we'll produce a workaround) the following - remove pingone-signals-sdk-ios from SPM, and add the framework manually to your Xcode project:

a. Download the framework:  https://assets.pingone.com/signals/ios-sdk/5.2.0/PingOneSignals.xcframework.zip
b. Drag the unzipped folder into your Xcode Frameworks folder.
c. Clean and run.

**Comment by learnwithgabbar** [comment]
@yizharkatif are you going to fix the SPM?

**Comment by yizharkatif** [comment]
Sure @learnwithgabbar, however this process might take days. We've already validated the fix.

**Comment by yizharkatif** [comment]
@learnwithgabbar please let me know if the fixed version works for you:
https://github.com/pingidentity/pingone-signals-sdk-ios/releases/tag/v5.2.1

**Comment by learnwithgabbar** [comment]
Thanks @yizharkatif 5.2.1 resolved our issue

**Comment by yizharkatif** [comment]
Thanks @learnwithgabbar for reporting it us know!
